# file version 0.1.3

version: "3.8"

services:
  # 必須確保各個 service name 及其 ports 或 expose
  # 與 Virtual-to-News/define.py 中的 host 及 port 完全一致

  virtual-to-news: # 這是 service name
    build: ./vtn_server # 這是資料夾路徑
    container_name: VTN-virtual-to-news # 這是 container 的名稱
    # 絕對路徑或相對路徑皆可。例如/home或./assets
    # host:container
    volumes: # 這是掛載磁區的地方（軟連結）
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
      - "./outputs:/app/outputs"
    # containers 及 host 都可以 access
    ports:
      - "25501:25501"


  file-server:
    build: ./file_server
    container_name: VTN-file-server
    volumes:
      - "./assets:/app/assets"
      - "./outputs:/app/outputs"
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
    ports:
      - "25500:25500"

  news-server:
    build: 
      context: ./news
      args:
        TORCH_VERSION: "${TORCH_VERSION}"
        TORCH_EXTRA_ARG: "${TORCH_EXTRA_ARG}"
        TORCH_EXTRA_URL: "${TORCH_EXTRA_URL}"
    container_name: VTN-news-server
    volumes:
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
      # 所有子專案(服務)共用的生成結果輸出資料夾
      - "./outputs:/app/outputs"
      # model + json 資料庫 軟連結
      - "./news/assets:/app/assets"
      #- "./assets/model/ckiplab:/app/assets/model/ckiplab"
      #- "./assets:/app/assets"
    expose:
      - 25505


  voice-server:
    build: 
      context: ./voice
      args:
        TORCH_VERSION: "${TORCH_VERSION}"
        TORCH_EXTRA_ARG: "${TORCH_EXTRA_ARG}"
        TORCH_EXTRA_URL: "${TORCH_EXTRA_URL}"
    container_name: VTN-voice-server
    volumes:
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
      # 所有子專案(服務)共用的生成結果輸出資料夾
      - "./outputs:/app/outputs"
      # model 軟連結
      - "./voice/synthesizer/saved_models/mandarin_200k.pt:/app/synthesizer/saved_models/mandarin_200k.pt"
      #- "./assets/model/synthesizer:/app/synthesizer/saved_models"
    
    # 只有 containers 可以存取
    # 存取方式是 http://<service-name>:25502/
    # e.g. http://voice-server:25502/image?date=2022-08-17&additional_info=some_info
    # 沒測試過，但是 args 中如果有空格應該會需要 URL encoding
    expose:
      - 25504

  lip-server:
    build: 
      context: ./lip
      args:
        TORCH_VERSION: "${TORCH_VERSION}"
        TORCH_EXTRA_ARG: "${TORCH_EXTRA_ARG}"
        TORCH_EXTRA_URL: "${TORCH_EXTRA_URL}"
    container_name: VTN-lip-server
    volumes:
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
      # 所有子專案(服務)共用的生成結果輸出資料夾
      - "./outputs:/app/outputs"
      # model 軟連結
      - "./lip/base_video:/app/base_video"
      - "./lip/checkpoints:/app/checkpoints"
      #- "./assets/model/checkpoints:/app/checkpoints"
      #- "./assets/base_video:/app/base_video"
      # Unity 用，將錄製完成的檔案軟連結到 container 中，讓 vtuber 的 FFmpeg 得以結合影片並放入 ./outputs/uuid/ 資料夾中
      - "${UNITY_VTUVER_PROJ_PATH}/unity_vtuber/Recordings:/app/unity_vtuber/Recordings"
    expose:
      - 25503

  vtuber-server:
    build: ./vtuber
    container_name: VTN-vtuber-server
    volumes:
      # 定義路徑、全域變數的檔案
      - "./define.py:/app/define.py"
      - "./outputs:/app/outputs"
      - "./lip/base_video:/app/lip/base_video"
      # Unity 用，將錄製完成的檔案軟連結到 container 中，讓 vtuber 的 FFmpeg 得以結合影片並放入 ./outputs/uuid/ 資料夾中
      - "${UNITY_VTUVER_PROJ_PATH}/Recordings:/app/unity_vtuber/Recordings"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 25502
