# file version 0.1.3

version: "3.8"

services:
  # 必須確保各個 service name 及其 ports 或 expose
  # 與 Virtual-to-News/define.py 中的 host 及 port 完全一致

  news-server:
    # cuda 使用
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all


  voice-server:
    # cuda 使用
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all


  lip-server:
    # cuda 使用
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              
  vtuber-server:
    # cuda 使用
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all

