visual_host = "visual-generating-server"
visual_port = "25504"
visual_server_url = f"http://{visual_host}:{visual_port}/"
lip_host = "visual-generating-server"
lip_port = "25506"
lip_server_url = f"http://{visual_host}:{visual_port}/"
voice_host = "voice-generating-server"
voice_port = "25502"
voice_server_url = f"http://{voice_host}:{voice_port}/"
news_host = "news-generating-server"
news_port = "25505"
news_server_url = f"http://{news_host}:{news_port}/"
virtual_to_news_host = "virtual-to-news"
virtual_to_news_port = "25501"
virtual_to_news_server_url = f"http://{virtual_to_news_host}:{virtual_to_news_port}/"

is_debug_mode = True
